# Site settings
title: Samuel Nimako-Mensah
email: samuel@nimacks.com
description: > # this means to ignore newlines until "baseurl:"
  Samuel's weblog on building distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nimacks.com" # the base hostname & protocol for your site
twitter_username: nimacks
github_username:  nimacks

# Build settings
markdown: kramdown
